<?php

namespace Container2rD7lyv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Erj0vfIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.erj0vfI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.erj0vfI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'calendarService' => ['services', 'App\\Service\\CalendarService', 'getCalendarServiceService', true],
            'mailToNewMember' => ['privates', 'App\\Service\\MailToNewMember', 'getMailToNewMemberService', true],
            'mailerInterface' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'calendarService' => 'App\\Service\\CalendarService',
            'mailToNewMember' => 'App\\Service\\MailToNewMember',
            'mailerInterface' => '?',
        ]);
    }
}
