<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGxkxXR7\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGxkxXR7/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerGxkxXR7.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerGxkxXR7\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerGxkxXR7\App_KernelProdContainer([
    'container.build_hash' => 'GxkxXR7',
    'container.build_id' => '75ba9ed3',
    'container.build_time' => 1602680173,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGxkxXR7');
