<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'index' => [[], ['_controller' => 'App\\Controller\\IndexController::index'], [], [['text', '/index']], [], []],
    'resume' => [[], ['_controller' => 'App\\Controller\\IndexController::resume'], [], [['text', '/resume']], [], []],
];
