<?php

namespace ContainerGxkxXR7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailToNewMemberService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\MailToNewMember' shared autowired service.
     *
     * @return \App\Service\MailToNewMember
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\MailToNewMember'] = new \App\Service\MailToNewMember();
    }
}
