<?php

namespace Container3ZA2gxx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_5XgtHvLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.5XgtHvL' shared service.
     *
     * @return \App\Service\Request
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Service\\CalendarService::store()": the $request argument is type-hinted with the non-existent class or interface: "App\\Service\\Request". Did you forget to add a use statement?');
    }
}
