<?php

namespace Container3ZA2gxx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T7jXptpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.T7jXptp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.T7jXptp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'calendarService' => ['services', 'App\\Service\\CalendarService', 'getCalendarServiceService', true],
        ], [
            'calendarService' => 'App\\Service\\CalendarService',
        ]);
    }
}
