<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1lm9J1G\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1lm9J1G/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1lm9J1G.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1lm9J1G\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1lm9J1G\App_KernelDevDebugContainer([
    'container.build_hash' => '1lm9J1G',
    'container.build_id' => '0e1099d6',
    'container.build_time' => 1610807997,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1lm9J1G');
