<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4xhEliz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4xhEliz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4xhEliz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4xhEliz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4xhEliz\App_KernelDevDebugContainer([
    'container.build_hash' => '4xhEliz',
    'container.build_id' => '09fce208',
    'container.build_time' => 1612974056,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4xhEliz');
