<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6wwomMQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6wwomMQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6wwomMQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6wwomMQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6wwomMQ\App_KernelDevDebugContainer([
    'container.build_hash' => '6wwomMQ',
    'container.build_id' => '5ddfe838',
    'container.build_time' => 1611938088,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6wwomMQ');
