<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'signup' => [
            'js' => [
                '/build/runtime.js',
                '/build/signup.js',
            ],
        ],
        'index' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~index.js',
                '/build/index.js',
            ],
        ],
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~app.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/app.css',
            ],
        ],
    ],
],

]];
